config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: "users#new"
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
# class ApplicationRecord < ActiveRecord::Base
#   primary_abstract_class
# end


class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  has_many :article_categories
  has_many :categories, through: :article_categories


  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord

  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  has_many :articles, dependent: :destroy
  validates :username, uniqueness: { case_sensitive: false }, presence: true, length: { in: 0..20 }
  VALID_EMAIL_REGEX = /\A[\w+\.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, uniqueness:{ case_sensitive: false}, presence: true, length: {minimum: 6, maximun: 105}, format: {with: VALID_EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action! "
      redirect_to login_path
    end
  end

  # add_flash_types :notice, :alert
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :update, :edit, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles =  Article.paginate(page: params[:page], per_page: 5)
  end

  def show
  end


  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article updated successfully. "
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity

    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end
  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end
  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own articles. "
      redirect_to article_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin, except: [:index, :show]


  def new
    @category = Category.new
  end
  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 3)
  end
  def index
    @categories =  Category.paginate(page: params[:page], per_page: 5)
  end
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created. "
      redirect_to @category

    else
      render :new, status: :unprocessable_entity
    end
  end
  def edit
    @category = Category.find(params[:id])
  end
  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      flash[:notice] = "Category updated successfully. "
      redirect_to @category
    else
      render :edit, status: :unprocessable_entity

    end
  end



  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admin can perform that action. "
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end
  def about

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully. "
      redirect_to user


    else
      flash.now[:alert] = "There was something wrong with your login detail. Please try again. "
      render :new, status: :unprocessable_entity

    end
  end
  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out. "
    redirect_to root_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update, :destroy]
  before_action :same_user, only: [:edit, :update, :destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end

  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome #{@user.username} to the Alpha Blog, you have successfully sign up your account! "
      redirect_to articles_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted."
    redirect_to articles_path
  end


  def edit
  end
  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated. "
      redirect_to user_path
    else
      redner :edit, status: :unprocessable_entity
    end
  end
  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 3)
  end


  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
  def set_user
    @user = User.find(params[:id])
  end
  def same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account. "
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = {size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "mt-3 shadow-lg rounded mx-auto d-block")
  end




end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
  <div class="container">
    <% @articles.each do |article| %>
      <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
          <div class="card text-center shadow mb-5 bg-body rounded">
            <div class="card-header">
              <% if article.user%>
                by <%= link_to article.user.username, user_path(article.user), class: "fst-italic text-decoration-none" %>
              <% end %>
              <% if article.categories.any? %>
                <div class="mt-2">
                  <%= render article.categories  %>
                </div>
              <% end %>
            </div>
            <div class="card-body">
              <h5 class="card-title"><%= link_to article.title.capitalize, article_path(article.id), {class: "text-success text-decoration-none"} %> </h5>
              <p class="card-text"><%= truncate(article.description.capitalize, length: 70) %></p>

              <%= link_to "View", article_path(article.id), method: :show, class: "btn btn-outline-success" %>

              <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                <%= link_to "Edit", edit_article_path(article.id), method: :edit, class: "btn btn-outline-info" %>
                <%= link_to "Delete", article_path(article.id), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-outline-danger" %>
              <% end %>

            </div>
            <div class="card-footer text-muted">
              <small>
                Created <%= time_ago_in_words(article.created_at) %> ago,
                edited <%= time_ago_in_words(article.updated_at) %> ago
              </small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/articles/_form.html.erb
<div class="container">
  <%= render "shared/errors", obj: @article %>
  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with(model: @article, class: "shadow rounded p-3 mb-3 bg-info", local: true) do |f| %>
        <div class="row form-group mt-5">
            <%= f.label :title, {class: "col-2 col-form-label text-light"} %>
          <div class="col-10">
            <%= f.text_field :title, {class: "form-control shadow rounded", placeholder: "Please enter article title here. "} %>
          </div>
        </div>
        <div class="row form-group mt-5">
          <%= f.label :description, {class: "col-2 col-form-label text-light"} %>
          <div class="col-10">
            <%= f.text_area :description, {class: "form-control shadow rounded", placeholder: "Please enter article content here. ", rows: "5"} %>
          </div>
        </div>
        <div class="row form-group mt-5">
          <%= f.label :Category, {class: "col-2 col-form-label text-light"} %>
          <div class="col-10">
            <%= f.collection_select(:category_ids, Category.all, :id, :name, {prompt: "Make your selection from the list below (can be empty)"}, {multiple: true, size: 3, class: "custom-select form-control shadow rounded"}) %>
          </div>
        </div>
        <div class="form-group mb-3 mt-4 text-center">
          <%= f.submit class: "btn btn-outline-light btn-lg"%>
        </div>
      <% end %>
    </div>
    <div class="container mb-5 mt-3 text-center">
      <%= link_to "[ Cancel and return to articles listing ]", articles_path, class: "text-info text-decoration-none" %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<main class="flex-shrink-0" id="page-content">
  <h1 class="text-center mt-4">Edit article</h1>
  <%= render 'articles/form'  %>
</main>

app/views/articles/index.html.erb
<main class="flex-shrink-0 mb-3" id="page-content">


  <h1 class="text-center mt-4">Articles listing page</h1>

  <div class="flickr_pagination mt-3">
    <%= will_paginate @articles, :container => false %>
  </div>


  <%= render 'articles/article' %>

  <br>
  <div class="container-md text-center justify-content-md-center">
    <%= link_to "Naw Article", new_article_path, class: "btn btn-success " %>
  </div>


  <div class="flickr_pagination mt-3 mb-3">
    <%= will_paginate @articles, :container => false %>
  </div>
</main>

app/views/articles/new.html.erb
<main class="flex-shrink-0" id="page-content">

  <h1 class="text-center mt-4">Create a new article</h1>
  <%= render "articles/form"  %>

</main>

app/views/articles/show.html.erb
<main class="container flex-shrink-0">
  <h2 class="text-center mt-4 text-capitalize"><span class="fw-light">Article: </span><%= @article.title %></h2>
  <div class="row justify-content-md-center mt-5">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-body rounded">
        <div class="card-header">
          Created by <span class="fst-italic"><%= @article.user.username %></span>
          <%= link_to gravatar_for(@article.user, size: 10), user_path(@article.user) %>

          <%if @article.categories.any? %>
            <div class="mt-2">

            <%= render @article.categories  %>
            </div>
          <% end %>
        </div>
        <div class="card-body">
          <div class="card-text text-start"><%= simple_format(@article.description.capitalize) %></div>

          <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
            <%= link_to "Edit", edit_article_path(@article.id), method: :edit, class: "btn btn-outline-info" %>
            <%= link_to "Delete", article_path(@article.id), data: {turbo_method: :delete, turbo_confirm:'Are you sure?'}, class: "btn btn-outline-danger" %>
          <% end %>

          <%= link_to "Return", articles_path, {class: "btn btn-outline-success"} %>
        </div>
        <div class="card-footer text-muted">
          <small>
            Created <%= time_ago_in_words(@article.created_at) %> ago,
            edited <%= time_ago_in_words(@article.updated_at) %> ago
          </small>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/categories/_article.html.erb
 <div class="container">
    <% @categories.each do |category| %>
      <div class="row justify-content-md-center">
        <div class="col-4 mt-4">
          <div class="card text-center shadow mb-5 bg-body rounded">
            <div class="card-body">
              <h5 class="card-title"><%= link_to category.name.capitalize, category_path(category.id), {class: "text-success text-decoration-none"} %> </h5>

              <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
            </div>
            <div class="card-footer text-muted">
              <small>
                Created <%= time_ago_in_words(category.created_at) %> ago,
                edited <%= time_ago_in_words(category.updated_at) %> ago
              </small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/categories/_category.html.erb
<%=link_to category.name, category_path(category), class: "badge rounded-pill text-bg-info mr-1 text-decoration-none text-white" %>

app/views/categories/_form.html.erb
<div class="container mt-3">
  <%= render "shared/errors", obj: @category %>
  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with(model: @category, class: "shadow rounded p-3 mb-3 bg-info", local: true) do |f| %>
        <div class="row form-group mt-5">
            <%= f.label :name, "Category Name", {class: "col-2 col-form-label text-light"} %>
          <div class="col-10">
            <%= f.text_field :name, {class: "form-control shadow rounded", placeholder: "Please enter category name here. "} %>
          </div>
        </div>

        <div class="form-group mb-3 mt-4 text-center">
          <%= f.submit "Submit", class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="container mb-5 mt-3 text-center">
      <%= link_to "[ Cancel and return to categories listing ]", categories_path, class: "text-info text-decoration-none" %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<main class="flex-shrink-0" id="page-content">
  <h1 class="text-center mt-4">Edit the Category</h1>
  <%= render 'categories/form'  %>
</main>

app/views/categories/index.html.erb
 <main class="flex-shrink-0 mb-3" id="page-content">


  <h1 class="text-center mt-4">Categories</h1>

  <div class="flickr_pagination mt-3">
    <%= will_paginate @categories, :container => false %>
  </div>



  <%= render 'categories/article' %>


  <br>
  <div class="container-md text-center justify-content-md-center">
    <%= link_to "New Category", new_category_path, class: "btn btn-success " %>
  </div>


  <div class="flickr_pagination mt-3 mb-3">
    <%= will_paginate @categories, :container => false %>
  </div>
</main>

app/views/categories/new.html.erb
<main class="flex-shrink-0" id="page-content">

  <h1 class="text-center mt-4">Create New Category</h1>

  <%= render "form"  %>


</main>

app/views/categories/show.html.erb
<main class="flex-shrink-0" id="page-content">

  <h1 class="text-center mt-4">Category: <%= @category.name %></h1>


  <div class="text-center mt-4">
    <% if logged_in? && current_user.admin?%>
      <%= link_to "Edit the Category", edit_category_path(@category), class: "btn btn-outline-info" %>
    <% end %>
  </div>
  <h3 class="text-center mt-4">Articles</h3>
  <div class="flickr_pagination mt-2 mb-2">
    <%= will_paginate @articles, :container => false %>
  </div>
  <%= render 'articles/article' %>
  <div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
  </div>

</main>

app/views/layouts/_footer.html.erb
  <footer class="bg-dark text-center text-white footer mt-auto py-3">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>

      <!-- Github -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright:
    <a class="text-white" href="/">Alpha_Blog.com</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if notice %>
    <div class="container alert alert-success text-center col-8 alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
  <% if alert %>
    <div class="container alert alert-danger text-center col-8 alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<header>
  <nav class="navbar navbar-expand-md customNav">
    <div class="container-fluid">
      <%= link_to "ALPHA BLOG",  root_path, {class: "navbar-brand", id: "logo"} %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Articles
            </a>
            <div class="dropdown-menu" aria-labelledby='navbarDropdown'>
              <% if logged_in? %>
                <%= link_to "New Article", new_article_path, {class: "dropdown-item"} %>
              <% end %>
              <%= link_to "All Articles", articles_path, {class: "dropdown-item"} %>

            </div>
          </li>

          <% if logged_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= "(Admin)" if current_user.admin? %>
               Profile <%= current_user.username.capitalize %>
              </a>
              <div class="dropdown-menu" aria-labelledby='navbarDropdown'>

                <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
                <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
                <%= link_to "Delete your profile", user_path(current_user), class: "dropdown-item text-danger", data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>

                <%= link_to "Logout", logout_path, class: "dropdown-item", data: {turbo_method: :delete, turbo_confirm:'Are you sure?'} %>
              </div>
            </li>


          <% else %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Profile
              </a>
              <div class="dropdown-menu" aria-labelledby='navbarDropdown'>

                <%= link_to "Login", login_path, {class: "dropdown-item"} %>
                <%= link_to "Sign Up", signup_path, {class: "dropdown-item"} %>

              </div>
            </li>
          <% end %>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categories
            </a>
            <div class="dropdown-menu" aria-labelledby='navbarDropdown'>
              <% if logged_in? && current_user.admin?%>
                <%= link_to "New Category", new_category_path, {class: "dropdown-item"} %>
              <% end %>
              <%= link_to "All Categories", categories_path, {class: "dropdown-item"} %>

            </div>
          </li>

          <li class="nav-item">
            <%= link_to "Show Bloggers", users_path, {class: "nav-link"} %>
          </li>

          <li class="nav-item">
            <%= link_to "About Us", about_path, {class: "nav-link"} %>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>Alpha_Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

  </head>

  <body class="d-flex flex-column h-100">
    <%= render "layouts/navigation" %>

    <%= render 'layouts/messages'%>



    <%= yield %>
    <%= render 'layouts/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

  </body>
</html>

app/views/pages/about.html.erb
<main class="container flex-shrink-0" >

</main>
<h1>This is about pages</h1>
<a href="/">link to home page</a>

app/views/pages/home.html.erb
<main class="flex-shrink-0 mb-3 mt-3" id="page-content">
  <div class="container" id="home-container">
      <div class="p-5 mb-4 rounded-3 text-center text-white jumbotron-bg">
          <div class="container-fluid py-5">
            <h1 class="display-5 fw-bold">ALPHA BLOG</h1>
            <hr class="my-4">
            <p class="col-md-8 fs-4" id="home-text">Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.</p>
            <%= link_to "Sign Up Today!", signup_path, {class: "btn btn-success btn-lg", type: "button"} %>
          </div>
        </div>
  </div>
</main>

app/views/shared/_errors.html.erb
  <% if obj.errors.any? %>
    <div class="container alert alert-danger text-center col-10 alert-dismissible fade show" role="alert">
      <h4 class="text-center mt-4 alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved. </h4>
      <hr>
        <% obj.errors.full_messages.each do |msg| %>
          <p class=""><%= msg %></p>
        <% end %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>

app/views/users/edit.html.erb
<main class="flex-shrink-0" id="page-content">

  <h1 class="text-center mt-4">Edit Your Profile</h1>

  <%= render "users/form"  %>


</main>

app/views/users/index.html.erb
<main class="flex-shrink-0" id="page-content">

  <h1 class="text-center mt-4">Alpha Bloggers</h1>
  <div class="flickr_pagination mt-3">
    <%= will_paginate @users, :container => false %>
  </div>
  <div class="container">
    <% @users.each do |user| %>
      <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
          <div class="card text-center shadow mb-5 bg-body rounded">
            <div class="card-header">
              <%= link_to "#{user.username}", user_path(user), class: "fst-italic, text-decoration-none" %>
            </div>
            <div class="card-body">
              <h5 class="card-title">
                <%= link_to gravatar_for(user, size: 150), user %>
              </h5>
              <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
              <%= link_to "View profile", user_path(user), method: :show, class: "btn btn-outline-success" %>

              <% if logged_in? %>
                <% if user == current_user %>
                  <%= link_to "Edit profile", edit_user_path(user), method: :edit, class: "btn btn-outline-info" %>
                <% end %>
                <%  if current_user.admin? %>
                  <%= link_to "Delete profile", user_path(user), data: {turbo_method: :delete, turbo_confirm: "Are you sure to delete the user and all associated articles? "}, class: "btn btn-outline-danger" %>
                <% end %>

              <% end %>

            </div>
            <div class="card-footer text-muted">
              <small>
                Joined <%= time_ago_in_words(user.created_at) %> ago
              </small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="flickr_pagination mb-3">
    <%= will_paginate @users, :container => false %>
  </div>

</main>

app/views/users/new.html.erb
<main class="flex-shrink-0" id="page-content">

  <h1 class="text-center mt-4">Sign Up for Alpha Blog</h1>

  <%= render "users/form"  %>


</main>

app/views/users/show.html.erb
<main class="flex-shrink-0" id="page-content">

  <h1 class="text-center mt-4">Profile of user: <%= @user.username %></h1>

  <%= gravatar_for @user, size: 200 %>
  <div class="text-center mt-4">
    <% if logged_in? && @user == current_user%>
      <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
    <% end %>
  </div>
  <h3 class="text-center mt-4">Articles</h3>
  <div class="flickr_pagination mt-2 mb-2">
    <%= will_paginate @articles, :container => false %>
  </div>
  <%= render 'articles/article' %>
  <div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
  </div>
</main>